### PR TITLE
chore: update Top.gg dependency 

### PR DESCRIPTION
**Pull request by officialpiyush**
## Details
- **Name:** [Top.gg](https://top.gg/) dependency update
- **Referencing Issue:** #105 
- **Description:** Updating the dependency with latest available package and some improvements in the intregation.
- **Code Review:** @XynoxTheDev & @Anish-Shobith.

## Checklist

- [x] Have you followed the [contributing guidelines](https://github.com/Dude-Perfect-Discord-Bot/Dude-Perfect/blob/main/.github/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

> **Note**: We will close your PR without comment if you do not check the boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by officialpiyush** [comment]
Would like some opinions, I think we shouldn't log after every successful post, all it's gonna do is spam the console.

**Comment by Anish-Shobith** [comment]
> Would like some opinions, I think we shouldn't log after every successful post, all it's gonna do is spam the console.

only if there is a error then send the error , I don't think so there is any requirement in logging each time it posts the data.

**Comment by officialpiyush** [comment]
> only if there is a error then send the error , I don't think so there is any requirement in logging each time it posts the data.

The library doesn't provide any event about the failed post(s), I've created a PR to the repo https://github.com/jpbberry/topgg-autoposter/pull/4 and I'll restore the error event file.

**Comment by XynoxTheDev** [comment]
Yes! Logging of errors has a point but every event of the Autopost is not to be recorded. It will only result in beautiful spam which we and our console don't want. If it's possible then only we should implement this update else we should discontinue using the top.gg integration.

**Comment by officialpiyush** [comment]
ding dong, review time

**Review by Anish-Shobith — APPROVED** [review]

**Review by XynoxTheDev — APPROVED** [review]

**Pull request merged**
