### PR TITLE
added more aliases

### PR DESCRIPTION
**Pull request by Dhruvin-Purohit**

### CODE REVIEW

**Review by XynoxTheDev — DISMISSED** [review]
Thanks, @Dhruvin-Purohit for contributing. **Aliases** to View permission command will be merged with **main**. Changes will be deployed to the public version soon.

**Review by Anish-Shobith — COMMENTED** [review]
Do we need a requirement of so many aliases ? isn't `viewperms` default name and `perms` enough ?

**Review by XynoxTheDev — COMMENTED** [review]
Yeah, as @Anish-Shobith said too many aliases isn't needed.

**Comment by Dhruvin-Purohit** [comment]
@Anish-Shobith 
@XynoxTheDev 

Now?

**Comment by Anish-Shobith** [comment]
Resolve conflicts

**Review by XynoxTheDev — APPROVED** [review]
Thanks, @Dhruvin-Purohit for contributing. **Aliases** to View permission command will be merged with **main**. Changes will be deployed to the public version soon.

**Pull request merged**
